language: c
os: linux
compiler:
 - gcc
 - clang
before_install:
 - wget http://lv2plug.in/spec/lv2-1.12.0.tar.bz2
 - tar xjf lv2-1.12.0.tar.bz2
install:
 - pushd lv2-1.12.0 && ./waf configure --prefix=/usr && ./waf build && sudo ./waf install && popd
before_script:
 - mkdir build && pushd build && cmake .. && popd
script:
 - pushd build && make && sudo make install && popd
